### ISSUE TITLE
Open up the wiki for contributions

### ISSUE THREAD

**Issue by StefanLobbenmeier** [CommandMC/EpicLinux#1]
Hi, I would like to contribute to the wiki :) Here is how to open it up https://docs.github.com/en/github/building-a-strong-community/changing-access-permissions-for-wikis

What I would like to add: Recommendation to use Lutris with a Lutris runtime to launch games (that fixed https://github.com/derrod/legendary/issues/188 for me)

Also guide on how to get HOB runnning:

# HOB
## Issue
HOB launcher does not launch

## Solution
Install vcrun2012 using winetricks

## Issue
HOB game has an AssertionException at Startup 

## Solution
From https://appdb.winehq.org/objectManager.php?sClass=version&iId=36043: Install d3dcompiler_43 using winetricks

**Comment by CommandMC** [comment]
Got the wiki opened now (I think). Feel free to add the guide (although I'd structure it a bit differently, all the headings aren't needed for the "one game = one page" structure I got going right now).

I personally don't like Lutris that much (their install scripts abstract the installation process a bit too much and there are a bunch of things included in those scripts that only help a small minority while complicating everything even more), plus launching games with Legendary most of the time doesn't work (as you're launching the game exe directly without giving it the parameters the Epic Games Store would give it (login token, profile name, etc)), so I wouldn't per-se recommend it

**Comment by StefanLobbenmeier** [comment]
I see, my issue - solution design is probably overkill  :) I created this page now with a more minimalistic approach: https://github.com/CommandMC/EpicLinux/wiki/HOB

**Comment by StefanLobbenmeier** [comment]
> their install scripts abstract the installation process a bit too much

I see, I use it to add the legendary games manually since there are no setup scripts for Epic Games games (at least did not find one so far

> as you're launching the game exe directly without giving it the parameters the Epic Games Store would give it (login token, profile name, etc)

Good point, so far this did not present an issue to me as the games I played were Single Player
