### ISSUE TITLE
[Wiki suggestion]: Celeste could work in OpenGL mode without dxvk tweaks.

### ISSUE THREAD

**Issue by Cooky-12** [CommandMC/EpicLinux#3]
according to "https://github.com/FNA-XNA/FNA/wiki/7%3A-FNA-Environment-Variables"
I launch the game with :
`FNA3D_FORCE_DRIVER=OpenGL wine Celeste.exe`
It runs smoothly like native game.
Maybe other FNA games will work in OpenGL mode too.

**Comment by CommandMC** [comment]
Thanks for letting me know. I've experimented with this a little more and it seems like there are actually two ways of setting this variable:
1. Just using environment variables like you did (`FNA3D_FORCE_DRIVER=OpenGL`)
2. Using `/gldevice:OpenGL` like the Wiki says

Additionally, Vulkan seems to work fine here as well.

I've updated the Wiki now, see https://github.com/CommandMC/EpicLinux/wiki/Celeste
